// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Entity
{
    public partial class Appointment
    {
        public int Id { get; set; }
        public string CustomerId { get; set; }
        public string UserId { get; set; }
        public DateTime? Date { get; set; }
        public string Status { get; set; }
    }
}